# Generated by Django 5.0.6 on 2026-07-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='ideal_answer_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='verdict',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
